import PMDL_WIFI from "./PMDL_WIFI";
import PMDL_EXCHANGE from "./PMDL_EXCHANGE";
import PMDL_INC_NINC from "./PMDL_INC_NINC";
import PMDL_SIM_CARD from "./PMDL_SIM_CARD";
import PMDL_USE_VALID from "./PMDL_USE_VALID";
import PMDL_PACKAGE_DESC from "./PMDL_PACKAGE_DESC";
import PMDL_REFUND_POLICY from "./PMDL_REFUND_POLICY";
import PMDL_EXCHANGE_VALID from "./PMDL_EXCHANGE_VALID";
import PMDL_NOTICE from "./PMDL_NOTICE";
import PMDL_GRAPHIC from "./PMDL_GRAPHIC";
import PMDL_SCHEDULE from "./PMDL_SCHEDULE";
import PMDL_EXTRA_FEE from "./PMDL_EXTRA_FEE";
import PMDL_NATIONALITY from "./PMDL_NATIONALITY";
import PMDL_HOWTO_SUMMARY from "./PMDL_HOWTO_SUMMARY";
import PMDL_VENUE_LOCATION from "./PMDL_VENUE_LOCATION";
import PMDL_SUGGESTED_ROUTE from "./PMDL_SUGGESTED_ROUTE";
import PMDL_PURCHASE_SUMMARY from "./PMDL_PURCHASE_SUMMARY";
import PMDL_EXCHANGE_LOCATION from "./PMDL_EXCHANGE_LOCATION";
import PMDL_INTRODUCE_SUMMARY from "./PMDL_INTRODUCE_SUMMARY";
import PMDL_EXPERIENCE_LOCATION from "./PMDL_EXPERIENCE_LOCATION";

// named re-exports if you still want them:
export { PMDL_WIFI };
export { PMDL_EXCHANGE };
export { PMDL_INC_NINC };
export { PMDL_SIM_CARD };
export { PMDL_USE_VALID };
export { PMDL_PACKAGE_DESC };
export { PMDL_REFUND_POLICY };
export { PMDL_EXCHANGE_VALID };
export { PMDL_NOTICE };
export { PMDL_GRAPHIC };
export { PMDL_SCHEDULE };
export { PMDL_EXTRA_FEE };
export { PMDL_NATIONALITY };
export { PMDL_HOWTO_SUMMARY };
export { PMDL_VENUE_LOCATION };
export { PMDL_SUGGESTED_ROUTE };
export { PMDL_PURCHASE_SUMMARY };
export { PMDL_EXCHANGE_LOCATION };
export { PMDL_INTRODUCE_SUMMARY };
export { PMDL_EXPERIENCE_LOCATION };

// default export object for easy lookup (Pdml[key])
export default {
  PMDL_WIFI,
  PMDL_EXCHANGE,
  PMDL_INC_NINC,
  PMDL_SIM_CARD,
  PMDL_USE_VALID,
  PMDL_PACKAGE_DESC,
  PMDL_REFUND_POLICY,
  PMDL_EXCHANGE_VALID,
  PMDL_NOTICE,
  PMDL_GRAPHIC,
  PMDL_SCHEDULE,
  PMDL_EXTRA_FEE,
  PMDL_NATIONALITY,
  PMDL_HOWTO_SUMMARY,
  PMDL_VENUE_LOCATION,
  PMDL_SUGGESTED_ROUTE,
  PMDL_PURCHASE_SUMMARY,
  PMDL_EXCHANGE_LOCATION,
  PMDL_INTRODUCE_SUMMARY,
  PMDL_EXPERIENCE_LOCATION,
};