export const routeStack = {
  '/title': {
    prev: '/index',
    next: '/country',
    title: '여행 이름을 정해주세요',
    subTitle1: '새 여행',
    subTitle2: null,
  },
  '/country': {
    prev: '/title',
    next: '/region',
    title: '여행지는 어디인가요?',
    subTitle1: '1. 여행 계획을 알려주세요',
    subTitle2: null,
  },
  '/region': {
    prev: '/country',
    next: '/day',
    title: '여행지는 어디인가요?',
    subTitle1: '1. 여행 계획을 알려주세요',
    subTitle2: null,
  },
  '/day': {
    prev: '/region',
    next: '/departure',
    title: '여행 날짜를 정해주세요',
    subTitle1: '1. 여행 계획을 알려주세요',
    subTitle2: '여행 시작일과 마지막 날을 선택해주세요',
  },
  '/departure': {
    prev: '/day',
    next: '/essential',
    title: '여행 출발지는 어디인가요?',
    subTitle1: '1. 여행 계획을 알려주세요',
    subTitle2: '선택하신 지역 근처의 공항과 기차역을 찾아봤어요',
  },
  '/essential': {
    prev: '/departure',
    next: '/who',
    title: '미리 정해 둔 장소가 있나요?',
    subTitle1: '1. 여행 계획을 알려주세요',
    subTitle2: '숙소는 최대 1개, 여행지는 최대 3개 추가할 수 있어요',
  },
  '/who': {
    prev: '/essential',
    next: '/transit-busy',
    title: '누구와 함께 가나요?',
    subTitle1: '2. 여행 스타일을 알아볼게요',
    subTitle2: '* 중복 선택 가능',
  },
  '/transit-busy': {
    prev: '/who',
    next: '/concept',
    title: '이동 수단과 여행 유형은 무엇인가요?',
    subTitle1: '2. 여행 스타일을 알아볼게요',
    subTitle2: '* 기본값 : 자동차(렌트카), 여유있는 일정',
  },
  '/concept': {
    prev: '/transit-busy',
    next: '/play',
    title: '여행 테마는 무엇인가요?',
    subTitle1: '2. 여행 스타일을 알아볼게요',
    subTitle2: '* 중복 선택 가능',
  },
  '/play': {
    prev: '/concept',
    next: '/tour',
    title: '하고 싶은 활동이 있나요?',
    subTitle1: '2. 여행 스타일을 알아볼게요',
    subTitle2: '* 중복 선택 가능',
  },
  '/tour': {
    prev: '/play',
    next: '/popular',
    title: '가고 싶은 장소는 어디인가요?',
    subTitle1: '2. 여행 스타일을 알아볼게요',
    subTitle2: '* 중복 선택 가능',
  },
  '/popular': {
    prev: '/tour',
    next: '/distance',
    title: '사람들이 자주 찾는 명소,\n얼마나 포함할까요?',
    subTitle1: '3. 여행지의 인기도를 선택해주세요',
    subTitle2: null,
  },
  '/distance': {
    prev: '/popular',
    next: '/final-check',
    title: '현재 위치에서 추천받을 여행 반경을 선택해주세요',
    subTitle1: '4. 원하는 반경의 지역을 추천해드려요',
    subTitle2: '그림은 이해를 돕기 위함으로 실제 결과와는 차이가 있을 수 있어요',
  },
  '/final-check': {
    prev: '/distance',
    next: '/',
    title: '여행 출발지는 어디인가요?',
    subTitle1: '1. 여행 계획을 알려주세요',
    subTitle2: '선택하신 지역 근처의 공항과 기차역을 찾아봤어요',
  },
};
