export const tendencyList = [
  {
    title: "누구와 떠나시나요?",
    multi: true,
    list: [
      "나홀로",
      "연인과",
      "친구와",
      "가족과",
      "효도",
      "자녀와",
      "반려동물과",
    ],
    photo: [
      "icon-person-default-man",
      "https://static.toss.im/2d-emojis/png/4x/u1F491.png",
      "icon-person-default-man",
      "https://static.toss.im/2d-emojis/png/4x/u1F468.png",
      "icon-person-default-man",
      "icon-emoji-grandparents",
      "icon-child",
      "https://static.toss.im/2d-emojis/png/4x/u1F9AE.png",
    ],
  },
  {
    title: "테마는 무엇인가요?",
    multi: true,
    list: [
      "힐링",
      "활동적인",
      "배움이 있는",
      "맛있는",
      "교통이 편한",
      "알뜰한",
    ],
    photo: [
      "https://static.toss.im/2d-emojis/png/4x/u1F340.png",
      "icon-activity-aos-blue",
      "icon-bulb-twinkle",
      "icon-spoon-chopsticks",
      "icon-road",
      "icon-coin-yellow",
    ],
  },
  {
    title: "무엇을 하고싶으신가요?",
    multi: true,
    list: ["드라이브", "산책", "이색체험", "레저 스포츠", "쇼핑", "시티투어"],
    photo: [
      "icon-car-handlebar",
      "https://static.toss.im/2d-emojis/png/4x/u1F6B6.png",
      "https://static.toss.im/2d-emojis/png/4x/u1FA82.png",
      "icon-motorcycle",
      "icon-shopping-bag-red",
      "https://static.toss.im/2d-emojis/png/4x/u1F306.png",
    ],
  },
  {
    title: "어디를 가고싶으신가요?",
    multi: true,
    list: ["바다", "산", "공원", "사진 명소", "실내여행지", "문화시설"],
    photo: [
      "https://static.toss.im/2d-emojis/png/4x/u1F30A.png",
      "https://static.toss.im/2d-emojis/png/4x/u26F0.png",
      "https://static.toss.im/2d-emojis/png/4x/u1F3DE.png",
      "icon-camera",
      "icon-building-yellow-transfer",
      "https://static.toss.im/2d-emojis/png/4x/u1F3B7.png",
    ],
  },
  {
    title: "어디를 가고싶으신가요?",
    multi: true,
    list: ["전통", "유적지", "성지", "사찰", "박물관"],
    photo: [
      "icon-blue-house",
      "https://static.toss.im/2d-emojis/png/4x/u1F3DB.png",
      "https://static.toss.im/2d-emojis/png/4x/u1F31E.png",
      "https://static.toss.im/2d-emojis/png/4x/u26EA.png",
      "https://static.toss.im/2d-emojis/png/4x/u1F38B.png",
      "https://static.toss.im/2d-emojis/png/4x/u1F3A8.png",
    ],
  },
];
