import type { TendencyData } from './tendencyTypes';

export const tendencyData: TendencyData = [
  {
    title: '누구와 떠나시나요?',
    multi: true,
    list: ['나홀로', '연인과', '친구와', '가족과', '효도', '자녀와', '반려동물과'],
    photo: [
      'icon-person-default-man',
      'https://static.toss.im/2d-emojis/png/4x/u1F491.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F468_u1F3FC_u200D_u1F91D_u200D_u1F468_u1F3FB.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F468_u200D_u1F469_u200D_u1F467_u200D_u1F466.png',
      'icon-emoji-grandparents',
      'icon-child',
      'https://static.toss.im/2d-emojis/png/4x/u1F9AE.png',
    ],
  },
  {
    title: '테마는 무엇인가요?',
    multi: true,
    list: ['힐링', '활동적인', '배움이 있는', '맛있는', '교통이 편한', '알뜰한'],
    photo: [
      'https://static.toss.im/2d-emojis/png/4x/u1F331.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F93F.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F4A1.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F37D.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F6E3.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F4B5.png',
    ],
  },
  {
    title: '무엇을 하고싶으신가요?',
    multi: true,
    list: ['레저 스포츠', '산책', '드라이브', '이색체험', '쇼핑', '시티투어'],
    photo: [
      'https://static.toss.im/2d-emojis/png/4x/u1F6B4.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F6B6.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F698.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F3C3.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F6CD.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F3E2.png',
    ],
  },
  {
    title: '가고 싶은 장소는 어디인가요?',
    multi: true,
    list: [
      '바다',
      '산',
      '실내여행지',
      '문화시설',
      '사진 명소',
      '유적지',
      '박물관',
      '전통',
      '공원',
      '사찰',
      '성지',
    ],
    photo: [
      'https://static.toss.im/2d-emojis/png/4x/u1F30A.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F3D4.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F3E2.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F3AD.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F4F7.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F3DB.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F3A8.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F3EF.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F3DE.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F54B.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F54C.png',
    ],
  },
  {
    title: '계절은 언제가 좋으신가요?',
    multi: true,
    list: ['봄', '여름', '가을', '겨울'],
    photo: [
      'https://static.toss.im/2d-emojis/png/4x/u1F33C.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F3DD.png',
      'https://static.toss.im/2d-emojis/png/4x/u1F341.png',
      'https://static.toss.im/2d-emojis/png/4x/u2744.png',
    ],
  },
];