// Auto generated by env plugin. DO NOT EDIT.
type Env = {
  GOOGLE_API_KEY: string;
  API_ROUTE: string;
  API_ROUTE_RELEASE: string;
  Google_Signin_Key: string;
  NAVER_API_KEY: string;
  NAVER_API_KEY_id: string;
  KAKAO_REST_API_KEY: string;
  KAKAO_NATIVE_KEY: string;
  Google_Ads_Key: string;
  Google_Ads_Banner_Android: string;
  Tour_API_KEY: string;
  CRYPTO_KEY: string;
  Tripadvisor_KEy: string;
};

interface ImportMeta {
  readonly env: Env & {};
}
