/* eslint-disable */
// This file is auto-generated by react-native-bedrock. DO NOT EDIT.
import { Route as _CountryRoute } from '../pages/country';
import { Route as _IndexRoute } from '../pages/';
import { Route as _RegionRoute } from '../pages/region';
import { Route as _TitleRoute } from '../pages/title';

declare module 'react-native-bedrock' {
  interface RegisterScreen {
    '/country': ReturnType<typeof _CountryRoute.useParams>;
    '/': ReturnType<typeof _IndexRoute.useParams>;
    '/region': ReturnType<typeof _RegionRoute.useParams>;
    '/title': ReturnType<typeof _TitleRoute.useParams>;
  }
}
