/* eslint-disable */
// This file is auto-generated by react-native-bedrock. DO NOT EDIT.
import { Route as _AddPlaceRoute } from '../pages/add-place';
import { Route as _EnrollBusyRoute } from '../pages/enroll/busy';
import { Route as _EnrollConceptRoute } from '../pages/enroll/concept';
import { Route as _EnrollCountryRoute } from '../pages/enroll/country';
import { Route as _EnrollDayRoute } from '../pages/enroll/day';
import { Route as _EnrollDepartureRoute } from '../pages/enroll/departure';
import { Route as _EnrollDistanceRoute } from '../pages/enroll/distance';
import { Route as _EnrollEssentialSearchRoute } from '../pages/enroll/essential-search';
import { Route as _EnrollEssentialRoute } from '../pages/enroll/essential';
import { Route as _EnrollPlayRoute } from '../pages/enroll/play';
import { Route as _EnrollPopularRoute } from '../pages/enroll/popular';
import { Route as _EnrollRegionRoute } from '../pages/enroll/region';
import { Route as _EnrollTitleRoute } from '../pages/enroll/title';
import { Route as _EnrollTourOneRoute } from '../pages/enroll/tour-one';
import { Route as _EnrollTourTwoRoute } from '../pages/enroll/tour-two';
import { Route as _EnrollTransitRoute } from '../pages/enroll/transit';
import { Route as _EnrollWhoRoute } from '../pages/enroll/who';
import { Route as _FinalCheckRoute } from '../pages/final-check';
import { Route as _IndexRoute } from '../pages/';
import { Route as _PresetDetailRoute } from '../pages/preset-detail';
import { Route as _PresetRoute } from '../pages/preset';
import { Route as _TimetableRoute } from '../pages/timetable';

declare module 'react-native-bedrock' {
  interface RegisterScreen {
    '/add-place': ReturnType<typeof _AddPlaceRoute.useParams>;
    '/enroll/busy': ReturnType<typeof _EnrollBusyRoute.useParams>;
    '/enroll/concept': ReturnType<typeof _EnrollConceptRoute.useParams>;
    '/enroll/country': ReturnType<typeof _EnrollCountryRoute.useParams>;
    '/enroll/day': ReturnType<typeof _EnrollDayRoute.useParams>;
    '/enroll/departure': ReturnType<typeof _EnrollDepartureRoute.useParams>;
    '/enroll/distance': ReturnType<typeof _EnrollDistanceRoute.useParams>;
    '/enroll/essential-search': ReturnType<typeof _EnrollEssentialSearchRoute.useParams>;
    '/enroll/essential': ReturnType<typeof _EnrollEssentialRoute.useParams>;
    '/enroll/play': ReturnType<typeof _EnrollPlayRoute.useParams>;
    '/enroll/popular': ReturnType<typeof _EnrollPopularRoute.useParams>;
    '/enroll/region': ReturnType<typeof _EnrollRegionRoute.useParams>;
    '/enroll/title': ReturnType<typeof _EnrollTitleRoute.useParams>;
    '/enroll/tour-one': ReturnType<typeof _EnrollTourOneRoute.useParams>;
    '/enroll/tour-two': ReturnType<typeof _EnrollTourTwoRoute.useParams>;
    '/enroll/transit': ReturnType<typeof _EnrollTransitRoute.useParams>;
    '/enroll/who': ReturnType<typeof _EnrollWhoRoute.useParams>;
    '/final-check': ReturnType<typeof _FinalCheckRoute.useParams>;
    '/': ReturnType<typeof _IndexRoute.useParams>;
    '/preset-detail': ReturnType<typeof _PresetDetailRoute.useParams>;
    '/preset': ReturnType<typeof _PresetRoute.useParams>;
    '/timetable': ReturnType<typeof _TimetableRoute.useParams>;
  }
}
